version: '3.3'
services:
  # PHP App:
  mhslvl-app:
    extends:
      file: ../PHP_App/docker-compose.yml
      service: mhslvl-app

  mhslvl-app-db:
    env_file:
      - ../PHP_App/.env
    extends:
      file: ../PHP_App/docker-compose.yml
      service: mhslvl-app-db
  
  # Client_SPA:
  mhslvl-client-spa:
    extends:
      file: ../Client_SPA/docker-compose.yml
      service: mhslvl-client-spa
  
  # SOAP_Service:
  mhslvl-soap:
    extends:
      file: ../SOAP_Service/docker-compose.yml
      service: mhslvl-soap
  
  mhslvl-soap-db:
    extends:
      file: ../SOAP_Service/docker-compose.yml
      service: mhslvl-soap-db
  
  # REST_Service:
  mhslvl-rest:
    extends:
      file: ../REST_Service/docker-compose.yml
      service: mhslvl-rest

  mhslvl-rest-db:
    extends:
      file: ../REST_Service/docker-compose.yml
      service: mhslvl-rest-db

  # phpmyadmin:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOSTS=mhslvl-rest-db,mhslvl-soap_db,mhslvl-app-db
      - PMA_PORT=3306
